osx_image: xcode11.3		
language: objective-c	
before_install:
  - chmod +x build.sh
install:
  - ./install_swiftlint.sh
script:
  - swiftlint
  - |		
    xcodebuild test \		
    -project frameworks/SwifteeCache.xcodeproj \		
    -scheme SwifteeCache \		
    -sdk iphonesimulator \			
    -destination 'platform=iOS Simulator,name=iPhone X,OS=latest' \
    | xcpretty
