osx_image: xcode11.3		
language: objective-c		
script:		
  - |		
    xcodebuild test \		
    -project frameworks/SwifteeCache.xcodeproj \		
    -scheme SwifteeCache \		
    -sdk iphonesimulator \			
    -destination 'platform=iOS Simulator,name=iPhone X,OS=latest' \
    | xcpretty
